// <auto-generated />
using HouseRental.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseRental.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260323180910_destinationCardEntityAdded3")]
    partial class destinationCardEntityAdded3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HouseRental.Shared.FeatureCard", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CardImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryID");

                    b.ToTable("FeatureCards");
                });
#pragma warning restore 612, 618
        }
    }
}
