// <auto-generated />
using HouseRental.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseRental.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260320163240_databaseupdated3")]
    partial class databaseupdated3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HouseRental.Shared.FeatureCard", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureCardDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FeatureCardImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FeatureCardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.ToTable("FeatureCards");
                });
#pragma warning restore 612, 618
        }
    }
}
